export const SET_STATUS = "SET_STATUS";
export const SET_LOADING = "SET_LOADING";
export const SET_QUESTIONS = "SET_QUESTIONS";
export const UPDATE_OPTION_SELECTION = "UPDATE_OPTION_SELECTION"
export const SET_VALIDATION_RESULT = "SET_VALIDATION_RESULT"
