export const SET_STATUS = "SET_STATUS";
export const SET_LOADING = "SET_LOADING";
export const SET_QUESTIONS = "SET_QUESTIONS";
export const SET_OPTION_SELECTION = "SET_OPTION_SELECTION";
export const SET_RESULT = "SET_RESULT";
