export const SET_STATUS = "SET_STATUS";
export const SET_LOADING = "SET_LOADING";
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const UPDATE_OPTION_SELECTION = "UPDATE_OPTION_SELECTION";
export const VALIDATION_RESULT = "VALIDATE_RESULT";
